version: "3"

services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  server:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
